### ISSUE TITLE
error on build 

### ISSUE THREAD

**Issue by JaphetMataImp** [Driversnote-Dev/react-native-helpscout-beacon#17]
A problem occurred configuring project ':react-native-helpscout-beacon'.
> Could not set unknown property 'classifier' for task ':react-native-helpscout-beacon:androidSourcesJar' of type org.gradle.api.tasks.bundling.Jar.

....afterEvaluate { project ->
    task androidSourcesJar(type: Jar) {
        classifier = 'sources'
        from android.sourceSets.main.java.srcDirs
        include '**/*.java'
    }

classifier -> archiveClassifier

**Comment by moritzmoritz** [comment]
Fixed in #20
