### ISSUE TITLE
'Beacon.h' file not found

### ISSUE THREAD

**Issue by steveliles** [Driversnote-Dev/react-native-helpscout-beacon#19]
From a clean initial install into an expo project (expo 50), when I try to build for ios i get:

```
 1 | #import "HelpscoutBeacon.h"
> 2 | #import "Beacon.h"
    |         ^ 'Beacon.h' file not found
  3 | #import <React/RCTBridgeModule.h>
  4 | 
  5 | @implementation HelpscoutBeacon
  ```
 @nitrique's branch https://github.com/nitrique/react-native-helpscout-beacon/tree/master seems to work (at least it builds, have not yet confirmed that the beacon works).

**Comment by nitrique** [comment]
Hey @steveliles, Yes it's in production on our side :)
Our PR is still in pending state :|

**Comment by nitrique** [comment]
@steveliles,

I have detached the fork from this repository to evolve further more the package as suggested by github documentation, obviously it closed the PR on this repo.

NPM package has been published in https://www.npmjs.com/package/@nitrique/react-native-helpscout-beacon

Release is v0.5.3

JS assets has been included in the release.

Feel free to contribute to the repo, any PR are welcome :)

**Comment by steveliles** [comment]
@nitrique legend! 🤩
