### ISSUE TITLE
HSBeacon file not found IOS

### ISSUE THREAD

**Issue by ugoconsonni** [Driversnote-Dev/react-native-helpscout-beacon#9]
Hi, i try ton install helpscout beacon but i have an error, HSBeacon file not found IOS.

Can you help me ?
<img width="342" alt="Capture d’écran 2021-11-16 à 01 59 20" src="https://user-images.githubusercontent.com/13661702/141876757-7ec5a7d7-4724-40d2-98fa-5a5102a08f07.png">
<img width="877" alt="Capture d’écran 2021-11-16 à 01 58 52" src="https://user-images.githubusercontent.com/13661702/141876759-7a0156b8-fe36-44c1-801c-736362eba880.png">
<img width="490" alt="Capture d’écran 2021-11-16 à 01 58 43" src="https://user-images.githubusercontent.com/13661702/141876761-ac0a8c87-06d6-49f0-8745-b18edee357a5.png">

**Comment by patrick-samy** [comment]
Same issue here. Were you able to solve this?

**Comment by syed-imam** [comment]
Tested and working version of Beacon SDK with this package on ios is `2.0.2`. Please use `pod 'Beacon', '2.0.2'` in your Podfile.

**Comment by moritzmoritz** [comment]
Fixed in #20
